### PR TITLE
Started the merging process.

### PR DESCRIPTION
**Pull request by haz**

### CODE REVIEW

**Comment by haz** [comment]
Hehehe...

```bash
muise@DESKTOP-52H4HJK:~/projects/pr2/src$ grep "cout << \"here" search/pr2/* | wc -l
grep: search/pr2/fd_integration: Is a directory
37
```

**Comment by haz** [comment]
@ssardina Ready to have a look!

**Comment by ssardina** [comment]
Will check this soon @haz , need to finish some course first..

**Comment by haz** [comment]
> Will check this soon @haz , need to finish some course first..

Time to have a gander?

**Comment by ssardina** [comment]
not yet... :wink: this is in my todo...

**Comment by haz** [comment]
Still on the stack, @ssardina ?

**Comment by ssardina** [comment]
I have aligned with the new pddl that doesn't have `AndEffect` class anymore. But I get:

```shell
$ python -m fondutils determinize --input tests/domain_03.pddl --output determinized-domain.pddl
usage: __main__.py [-h] --input INPUT [--output OUTPUT] [--outproblem OUTPROBLEM] [--prefix PREFIX] [--suffix SUFFIX] [--console] {check,determinize,normalize}
__main__.py: error: --outproblem is required for domain+problem input
```

I think it is because `tests/domain_03.pddl` is not just a domain, it also has the problem! :confused:

**Comment by ssardina** [comment]
OK @haz, sorry it took me so long to review this... I have checked it and thanks for putting together our two versions, yours with mine at [fond2allout](https://github.com/ssardina-research/fond2allout); I guess I will park my project and contribute here as needed.

I have checked and tested the code quite a bit, and fix or improve a few things:

- fixed the issue with the new pddl, which has changed the `AndEffect` to just `And` #3 
- change the way we handle files that contain problem files besides domain. Instead of requiring always to give an `--outproblem` where to put the domain, by default is is written with the new domain (as in the input which were together), but if `--outproblem` is provided, then problem is factored out to its own file (this could be good when normalizing, to separate problem from domain I guess)
- iteration on readme, did a few fixes and improvements (e.g., suffix and prefix, etc)
- added a 05 example that includes a quite complex effect
- refactor test example pddl files to make it clear which ones contain domain, problem, or domain and problem

All done! I think you can continue and maybe merge into main. :wink: 

Hope you had a good xmas and you finish 2024 well and happy, to start a fresh and promising 2025! :tada: :tada: :fireworks: 

(BTW, I couldn't formally reviewed it in GH as I am not a reviewer; I could have requested but it would be too late and I needed to do this today before I am going way :camping: tomorrow for 20 days!)

**Comment by ssardina** [comment]
> Still on the stack, @ssardina ?

unstacked! popped! :heavy_check_mark:

**Comment by haz** [comment]
Amazing, thank you, @ssardina !!

Only other change I can recall that went into `pddl` (and is relevant), is the fix you had in place for the unique parsing is no longer required. I'll cross-check that one and make the change on a separate PR.

And, ya, the idea was that we'd merge initiatives -- this one was meant to be "ours" and not "mine -vs- yours" -- it's largely your code, after all! I'm on the dev side of `pddl`, so can get changes happening over there when we need it.

Thanks again, and have a wonderful holiday break!

**Comment by haz** [comment]
Hope it's ok, but I broke with protocol and just pushed it direct to `main`: https://github.com/AI-Planning/fond-utils/commit/c5a9b1facb2181e76091831c14b50ea6f2e8eb2d

This was a stub you left while we got our act together on your work over with `pddl`: https://github.com/AI-Planning/pddl/pull/109

Essentially you had the same implementation in this `fond-utils` repo until the `pddl` had a version bump (which has subsequently gone in). Thanks again for your work on it all!

**Pull request merged**
